=== LuisCabelloCabanillas/1-DAM-Safa/Lenguajes de marcas/XML/ExDAW/piratas.dtd
<!ELEMENT piratas (pirata+)>
<!ELEMENT pirata (nombre, imagen, datos_actor, peliculas, roles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT datos_actor (nombre, apellidos, sexo, nacimiento)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (datos)>
<!ELEMENT datos (titulo, saga)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT saga (#PCDATA)>
<!ELEMENT roles (rol+)>
<!ELEMENT rol (tipo_rol, barco)>
<!ELEMENT tipo_rol (#PCDATA)>
<!ELEMENT barco (#PCDATA)>
<!ATTLIST sexo value (M|F|NB) #REQUIRED>
<!ATTLIST tipo_rol value (CAPITÁN|TRIPULANTE|GRUMETE) #REQUIRED>

=== LuisCabelloCabanillas/1-DAM-Safa/Lenguajes de marcas/XML/ExDAW/piratas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE piratas SYSTEM "piratas.dtd">
<piratas>
    <pirata>
        <nombre>Jack Sparrow</nombre>
        <imagen>https://sparrow.jpg</imagen>
        <datos_actor>
            <nombre>Johnny</nombre>
            <apellidos>Deep</apellidos>
            <sexo>M</sexo>
            <nacimiento>09-06-1963</nacimiento>
        </datos_actor>
        <peliculas>
            <pelicula>
                <datos>
                    <titulo>La maldición de la perla negra</titulo>
                    <saga>Piratas del Caribe</saga>
                </datos>
            </pelicula>
        </peliculas>
        <roles>
            <rol>
                <tipo_rol>CAPITÁN</tipo_rol>
                <barco>La Perla Negra</barco>
            </rol>
        </roles>
    </pirata>
</piratas>
